#!/usr/bin/env python3
"""Generate material-definition JSON for the remaining crystalline materials.

Bases are expanded from the published Wyckoff parameters of each space group
rather than typed out, so the generated coordinates are reproducible from the
cited structure determinations.  Re-run only when the table changes.

Usage:  python tools/gen_crystal_materials.py
"""

import json
import os
from fractions import Fraction

OUT = os.path.join(os.path.dirname(__file__), "..", "materia", "materials", "library")
T3 = 1.0 / 3.0
T23 = 2.0 / 3.0


def r(x):
    return round(float(x) % 1.0, 7)


def diamond_basis(sym_a, sym_b):
    """Diamond-cubic / zinc-blende conventional cell (8 sites)."""
    fcc = [(0, 0, 0), (0, .5, .5), (.5, 0, .5), (.5, .5, 0)]
    out = []
    for f in fcc:
        out.append({"element": sym_a, "fractional": [r(v) for v in f],
                    "label": f"{sym_a}(a)", "wyckoff": "4a"})
    for f in fcc:
        out.append({"element": sym_b,
                    "fractional": [r(v + .25) for v in f],
                    "label": f"{sym_b}(c)", "wyckoff": "4c"})
    return out


def wurtzite_basis(cation, anion, u):
    return [
        {"element": cation, "fractional": [r(T3), r(T23), 0.0], "label": f"{cation}(1)", "wyckoff": "2b"},
        {"element": cation, "fractional": [r(T23), r(T3), 0.5], "label": f"{cation}(2)", "wyckoff": "2b"},
        {"element": anion, "fractional": [r(T3), r(T23), r(u)], "label": f"{anion}(1)", "wyckoff": "2b"},
        {"element": anion, "fractional": [r(T23), r(T3), r(u + .5)], "label": f"{anion}(2)", "wyckoff": "2b"},
    ]


def hbn_basis():
    return [
        {"element": "B", "fractional": [r(T3), r(T23), 0.25], "label": "B", "wyckoff": "2c"},
        {"element": "B", "fractional": [r(T23), r(T3), 0.75], "label": "B", "wyckoff": "2c"},
        {"element": "N", "fractional": [r(T23), r(T3), 0.25], "label": "N", "wyckoff": "2d"},
        {"element": "N", "fractional": [r(T3), r(T23), 0.75], "label": "N", "wyckoff": "2d"},
    ]


def tmd_2h_basis(metal, chalc, z):
    """2H-MX2 (P6_3/mmc): M on 2c, X on 4f with internal parameter z."""
    return [
        {"element": metal, "fractional": [r(T3), r(T23), 0.25], "label": metal, "wyckoff": "2c"},
        {"element": metal, "fractional": [r(T23), r(T3), 0.75], "label": metal, "wyckoff": "2c"},
        {"element": chalc, "fractional": [r(T3), r(T23), r(z)], "label": chalc, "wyckoff": "4f"},
        {"element": chalc, "fractional": [r(T23), r(T3), r(z + .5)], "label": chalc, "wyckoff": "4f"},
        {"element": chalc, "fractional": [r(T23), r(T3), r(-z)], "label": chalc, "wyckoff": "4f"},
        {"element": chalc, "fractional": [r(T3), r(T23), r(-z + .5)], "label": chalc, "wyckoff": "4f"},
    ]


def corundum_basis(z_al, x_o):
    """alpha-Al2O3, R-3c (#167), hexagonal setting: Al on 12c, O on 18e."""
    centering = [(0, 0, 0), (T23, T3, T3), (T3, T23, T23)]
    al_core = [(0, 0, z_al), (0, 0, -z_al), (0, 0, z_al + .5), (0, 0, -z_al + .5)]
    o_core = [(x_o, 0, .25), (0, x_o, .25), (-x_o, -x_o, .25),
              (-x_o, 0, .75), (0, -x_o, .75), (x_o, x_o, .75)]
    out = []
    for c in centering:
        for p in al_core:
            out.append({"element": "Al", "fractional": [r(p[i] + c[i]) for i in range(3)],
                        "label": "Al", "wyckoff": "12c"})
    for c in centering:
        for p in o_core:
            out.append({"element": "O", "fractional": [r(p[i] + c[i]) for i in range(3)],
                        "label": "O", "wyckoff": "18e"})
    return out


def quartz_basis(x_si, x_o, y_o, z_o):
    """alpha-SiO2 in the P3_2 21 setting (#154): Si on 3a, O on 6c.

    The general positions are those generated by the 3_2 screw
    (x, y, z) -> (-y, x-y, z+2/3) and the two-fold axis (x, y, z) -> (y, x, -z).
    The origin convention matters: with Si on 3a at z = 2/3 the oxygen z from
    Levien et al. must be taken as 0.7858, not 0.1191. The resulting cell is
    checked against the published Si-O and O-O distances in
    tests/validation/test_physical_validation.py.
    """
    si = [(x_si, 0.0, T23), (0.0, x_si, T3), (-x_si, -x_si, 0.0)]
    x, y, z = x_o, y_o, z_o
    o = [(x, y, z), (-y, x - y, z + T23), (-x + y, -x, z + T3),
         (y, x, -z), (-x, -x + y, -z + T23), (x - y, -y, -z + T3)]
    out = [{"element": "Si", "fractional": [r(v) for v in p], "label": "Si",
            "wyckoff": "3a"} for p in si]
    out += [{"element": "O", "fractional": [r(v) for v in p], "label": "O",
             "wyckoff": "6c"} for p in o]
    return out


MATERIALS = []


def add(**kw):
    MATERIALS.append(kw)


add(
    id="germanium", name="Germanium", formula="Ge", aliases=["Ge"],
    category="elemental semiconductor", prototype="diamond-cubic",
    sg=(227, "Fd-3m"), system="cubic", a=5.65785, c=None,
    lattice_source="J. Donohue, The Structures of the Elements (Wiley, 1974)",
    basis=diamond_basis("Ge", "Ge"),
    orientations=[[1, 0, 0], [1, 1, 0], [1, 1, 1]],
    props={
        "density": (5.323, "g/cm^3", "298 K", "CRC Handbook"),
        "band_gap": (0.661, "eV", "300 K, indirect (L point)", "S. M. Sze, Physics of Semiconductor Devices"),
        "band_gap_type": ("indirect", "", "", "definition"),
        "dielectric_constant": (16.0, "", "static", "S. M. Sze"),
        "melting_point": (1211.4, "K", "", "CRC Handbook"),
        "thermal_conductivity": (60.2, "W/(m K)", "300 K", "CRC Handbook"),
        "elastic_C11": (128.9, "GPa", "300 K", "H. J. McSkimin, J. Appl. Phys. 24 (1953) 988"),
        "elastic_C12": (48.3, "GPa", "300 K", "H. J. McSkimin, J. Appl. Phys. 24 (1953) 988"),
        "elastic_C44": (67.1, "GPa", "300 K", "H. J. McSkimin, J. Appl. Phys. 24 (1953) 988"),
        "cohesive_energy": (3.85, "eV/atom", "", "C. Kittel, Introduction to Solid State Physics, 8th ed."),
    },
    models={"relax": "stillinger-weber-ge", "electronic": "tight-binding-sp3s",
            "stm": "tersoff-hamann", "high-fidelity": "external:gpaw"},
)

add(
    id="diamond", name="Diamond", formula="C", aliases=["C-diamond"],
    category="wide-bandgap elemental semiconductor", prototype="diamond-cubic",
    sg=(227, "Fd-3m"), system="cubic", a=3.56712, c=None,
    lattice_source="T. Hom, W. Kiszenick, B. Post, J. Appl. Cryst. 8 (1975) 457",
    basis=diamond_basis("C", "C"),
    orientations=[[1, 0, 0], [1, 1, 0], [1, 1, 1]],
    props={
        "density": (3.515, "g/cm^3", "298 K", "CRC Handbook"),
        "band_gap": (5.47, "eV", "300 K, indirect", "C. D. Clark et al., Proc. R. Soc. A 277 (1964) 312"),
        "band_gap_type": ("indirect", "", "", "definition"),
        "dielectric_constant": (5.7, "", "static", "CRC Handbook"),
        "thermal_conductivity": (2200, "W/(m K)", "300 K, type IIa", "CRC Handbook"),
        "elastic_C11": (1079, "GPa", "300 K", "H. J. McSkimin and P. Andreatch, J. Appl. Phys. 43 (1972) 2944"),
        "elastic_C12": (124, "GPa", "300 K", "H. J. McSkimin and P. Andreatch, J. Appl. Phys. 43 (1972) 2944"),
        "elastic_C44": (578, "GPa", "300 K", "H. J. McSkimin and P. Andreatch, J. Appl. Phys. 43 (1972) 2944"),
        "cohesive_energy": (7.37, "eV/atom", "", "C. Kittel, Introduction to Solid State Physics, 8th ed."),
    },
    models={"relax": "lennard-jones-generic", "electronic": "unsupported",
            "stm": "tersoff-hamann", "high-fidelity": "external:quantum-espresso"},
)

add(
    id="indium_phosphide", name="Indium phosphide", formula="InP", aliases=["InP"],
    category="III-V compound semiconductor", prototype="zinc-blende",
    sg=(216, "F-43m"), system="cubic", a=5.8687, c=None,
    lattice_source="Landolt-Boernstein III/17a, semiconductor structure data",
    basis=diamond_basis("In", "P"),
    orientations=[[1, 0, 0], [1, 1, 0], [1, 1, 1]],
    props={
        "density": (4.81, "g/cm^3", "300 K", "CRC Handbook"),
        "band_gap": (1.344, "eV", "300 K, direct at Gamma", "S. M. Sze"),
        "band_gap_type": ("direct", "", "", "definition"),
        "dielectric_constant": (12.5, "", "static", "S. M. Sze"),
        "melting_point": (1335, "K", "", "CRC Handbook"),
        "thermal_conductivity": (68, "W/(m K)", "300 K", "CRC Handbook"),
        "elastic_C11": (101.1, "GPa", "300 K", "Landolt-Boernstein III/17a"),
        "elastic_C12": (56.1, "GPa", "300 K", "Landolt-Boernstein III/17a"),
        "elastic_C44": (45.6, "GPa", "300 K", "Landolt-Boernstein III/17a"),
    },
    models={"relax": "unsupported", "electronic": "unsupported",
            "stm": "tersoff-hamann", "high-fidelity": "external:quantum-espresso"},
)

add(
    id="silicon_carbide_3c", name="Silicon carbide (3C polytype)", formula="SiC",
    aliases=["3C-SiC", "beta-SiC", "cubic silicon carbide"],
    category="wide-bandgap compound semiconductor", prototype="zinc-blende",
    sg=(216, "F-43m"), system="cubic", a=4.3596, c=None,
    lattice_source="A. Taylor and R. M. Jones, in Silicon Carbide - A High Temperature Semiconductor (Pergamon, 1960)",
    basis=diamond_basis("Si", "C"),
    orientations=[[1, 0, 0], [1, 1, 0], [1, 1, 1]],
    props={
        "density": (3.21, "g/cm^3", "300 K", "CRC Handbook"),
        "band_gap": (2.36, "eV", "300 K, indirect", "W. J. Choyke and G. Pensl, MRS Bull. 22 (1997) 25"),
        "band_gap_type": ("indirect", "", "", "definition"),
        "dielectric_constant": (9.72, "", "static", "Landolt-Boernstein III/17a"),
        "thermal_conductivity": (360, "W/(m K)", "300 K", "CRC Handbook"),
        "elastic_C11": (390, "GPa", "300 K", "K. Kamitani et al., J. Appl. Phys. 82 (1997) 3152"),
        "elastic_C12": (142, "GPa", "300 K", "K. Kamitani et al., J. Appl. Phys. 82 (1997) 3152"),
        "elastic_C44": (256, "GPa", "300 K", "K. Kamitani et al., J. Appl. Phys. 82 (1997) 3152"),
    },
    models={"relax": "stillinger-weber-sic", "electronic": "unsupported",
            "stm": "tersoff-hamann", "high-fidelity": "external:quantum-espresso"},
)

add(
    id="gallium_nitride", name="Gallium nitride", formula="GaN", aliases=["GaN", "w-GaN"],
    category="III-V wide-bandgap semiconductor", prototype="wurtzite",
    sg=(186, "P6_3mc"), system="hexagonal", a=3.1890, c=5.1850,
    lattice_source="H. Schulz and K. H. Thiemann, Solid State Commun. 23 (1977) 815",
    basis=wurtzite_basis("Ga", "N", 0.3770),
    orientations=[[0, 0, 1], [1, 1, 0], [1, 0, 0]],
    props={
        "density": (6.15, "g/cm^3", "300 K", "CRC Handbook"),
        "band_gap": (3.39, "eV", "300 K, direct", "B. Monemar, Phys. Rev. B 10 (1974) 676"),
        "band_gap_type": ("direct", "", "", "definition"),
        "dielectric_constant": (8.9, "", "static, parallel c", "Landolt-Boernstein III/17a"),
        "thermal_conductivity": (130, "W/(m K)", "300 K", "CRC Handbook"),
        "elastic_C11": (390, "GPa", "300 K", "A. Polian et al., J. Appl. Phys. 79 (1996) 3343"),
        "elastic_C12": (145, "GPa", "300 K", "A. Polian et al., J. Appl. Phys. 79 (1996) 3343"),
        "elastic_C44": (105, "GPa", "300 K", "A. Polian et al., J. Appl. Phys. 79 (1996) 3343"),
        "spontaneous_polarization": (-0.029, "C/m^2", "along +c", "F. Bernardini, V. Fiorentini, D. Vanderbilt, Phys. Rev. B 56 (1997) R10024"),
    },
    models={"relax": "unsupported", "electronic": "unsupported",
            "stm": "tersoff-hamann", "high-fidelity": "external:quantum-espresso"},
)

add(
    id="hexagonal_boron_nitride", name="Hexagonal boron nitride", formula="BN",
    aliases=["h-BN", "hBN", "white graphene"],
    category="two-dimensional insulator", prototype="hexagonal-layered",
    sg=(194, "P6_3/mmc"), system="hexagonal", a=2.5040, c=6.6612,
    lattice_source="R. S. Pease, Acta Cryst. 5 (1952) 356",
    basis=hbn_basis(),
    orientations=[[0, 0, 1]],
    props={
        "density": (2.28, "g/cm^3", "300 K", "CRC Handbook"),
        "band_gap": (5.955, "eV", "bulk, indirect", "K. Watanabe, T. Taniguchi, H. Kanda, Nature Mater. 3 (2004) 404"),
        "band_gap_type": ("indirect", "", "", "definition"),
        "dielectric_constant": (5.06, "", "perpendicular to c", "R. Geick, C. H. Perry, G. Rupprecht, Phys. Rev. 146 (1966) 543"),
        "bond_length": (1.4457, "A", "in-plane B-N, derived a/sqrt(3)", "calculated"),
    },
    models={"relax": "lennard-jones-generic", "electronic": "unsupported",
            "stm": "tersoff-hamann", "high-fidelity": "external:gpaw"},
)

add(
    id="molybdenum_disulfide", name="Molybdenum disulfide (2H)", formula="MoS2",
    aliases=["MoS2", "2H-MoS2", "molybdenite"],
    category="transition-metal dichalcogenide", prototype="2h-tmd",
    sg=(194, "P6_3/mmc"), system="hexagonal", a=3.1612, c=12.2985,
    lattice_source="B. Schoenfeld, J. J. Huang, S. C. Moss, Acta Cryst. B 39 (1983) 404",
    basis=tmd_2h_basis("Mo", "S", 0.6210),
    orientations=[[0, 0, 1]],
    props={
        "density": (5.06, "g/cm^3", "300 K", "CRC Handbook"),
        "band_gap": (1.29, "eV", "bulk, indirect, 300 K", "K. F. Mak et al., Phys. Rev. Lett. 105 (2010) 136805"),
        "band_gap_type": ("indirect (bulk); direct 1.8 eV for the monolayer", "", "", "K. F. Mak et al., Phys. Rev. Lett. 105 (2010) 136805"),
        "monolayer_band_gap": (1.8, "eV", "monolayer, direct at K", "K. F. Mak et al., Phys. Rev. Lett. 105 (2010) 136805"),
        "bond_length": (2.418, "A", "Mo-S, derived from a, c and z", "calculated"),
    },
    models={"relax": "lennard-jones-generic", "electronic": "unsupported",
            "stm": "tersoff-hamann", "high-fidelity": "external:gpaw"},
)

add(
    id="tungsten_diselenide", name="Tungsten diselenide (2H)", formula="WSe2",
    aliases=["WSe2", "2H-WSe2"],
    category="transition-metal dichalcogenide", prototype="2h-tmd",
    sg=(194, "P6_3/mmc"), system="hexagonal", a=3.2820, c=12.9600,
    lattice_source="W. J. Schutte, J. L. de Boer, F. Jellinek, J. Solid State Chem. 70 (1987) 207",
    basis=tmd_2h_basis("W", "Se", 0.6210),
    orientations=[[0, 0, 1]],
    props={
        "density": (9.32, "g/cm^3", "300 K", "CRC Handbook"),
        "band_gap": (1.2, "eV", "bulk, indirect", "W. Zhao et al., ACS Nano 7 (2013) 791"),
        "band_gap_type": ("indirect (bulk); direct ~1.65 eV for the monolayer", "", "", "W. Zhao et al., ACS Nano 7 (2013) 791"),
        "monolayer_band_gap": (1.65, "eV", "monolayer, direct at K", "W. Zhao et al., ACS Nano 7 (2013) 791"),
    },
    models={"relax": "lennard-jones-generic", "electronic": "unsupported",
            "stm": "tersoff-hamann", "high-fidelity": "external:gpaw"},
)

add(
    id="sapphire", name="Sapphire (alpha-alumina)", formula="Al2O3",
    aliases=["Al2O3", "alpha-Al2O3", "aluminium oxide", "aluminum oxide", "corundum"],
    category="oxide insulator", prototype="corundum",
    sg=(167, "R-3c"), system="hexagonal", a=4.7591, c=12.9894,
    lattice_source="N. Ishizawa et al., Acta Cryst. B 36 (1980) 228",
    basis=corundum_basis(0.35216, 0.30624),
    orientations=[[0, 0, 1], [1, 1, 0], [1, 0, 2]],
    props={
        "density": (3.98, "g/cm^3", "300 K", "CRC Handbook"),
        "band_gap": (8.8, "eV", "300 K, optical", "R. H. French, J. Am. Ceram. Soc. 73 (1990) 477"),
        "band_gap_type": ("wide-gap insulator", "", "", "definition"),
        "dielectric_constant": (9.4, "", "static, perpendicular c", "CRC Handbook"),
        "melting_point": (2345, "K", "", "CRC Handbook"),
        "thermal_conductivity": (30, "W/(m K)", "300 K", "CRC Handbook"),
    },
    models={"relax": "unsupported", "electronic": "unsupported",
            "stm": "unsupported", "high-fidelity": "external:quantum-espresso"},
    note="Alumina is a wide-gap insulator: tunnelling STM imaging of the bare surface is not physically meaningful, and the STM model returns an explicit unsupported result for it.",
)

add(
    id="silicon_dioxide", name="Silicon dioxide (alpha-quartz)", formula="SiO2",
    aliases=["SiO2", "quartz", "alpha-quartz", "silica"],
    category="oxide insulator", prototype="alpha-quartz",
    sg=(154, "P3_221"), system="hexagonal", a=4.9134, c=5.4052,
    lattice_source="L. Levien, C. T. Prewitt, D. J. Weidner, Am. Mineral. 65 (1980) 920",
    basis=quartz_basis(0.4697, 0.4135, 0.2669, 0.7858),
    orientations=[[0, 0, 1], [1, 0, 0]],
    props={
        "density": (2.648, "g/cm^3", "300 K", "CRC Handbook"),
        "band_gap": (8.9, "eV", "300 K", "T. H. DiStefano and D. E. Eastman, Solid State Commun. 9 (1971) 2259"),
        "band_gap_type": ("wide-gap insulator", "", "", "definition"),
        "dielectric_constant": (3.9, "", "static, thermal amorphous SiO2", "S. M. Sze"),
        "melting_point": (1983, "K", "", "CRC Handbook"),
    },
    models={"relax": "unsupported", "electronic": "unsupported",
            "stm": "unsupported", "high-fidelity": "external:cp2k"},
    note="Thermal gate oxide is amorphous; the shipped definition is crystalline alpha-quartz. An amorphous SiO2 model is on the roadmap and is not provided in v0.1.",
)


def prop_block(props):
    out = {}
    for key, (value, unit, conditions, source) in props.items():
        entry = {"value": value, "unit": unit}
        if conditions:
            entry["conditions"] = conditions
        entry["source"] = source
        if source == "calculated":
            entry["origin"] = "calculated"
            entry["source"] = "derived from the lattice parameters in this file"
        out[key] = entry
    return out


def main():
    for m in MATERIALS:
        lattice = {"a": m["a"], "unit": "A", "system": m["system"],
                   "temperature_K": 300, "source": m["lattice_source"]}
        if m["c"] is not None:
            lattice["c"] = m["c"]
        doc = {
            "schema_version": "1.0",
            "id": m["id"], "name": m["name"], "formula": m["formula"],
            "aliases": m["aliases"], "category": m["category"],
            "structure": {
                "prototype": m["prototype"],
                "space_group": {"number": m["sg"][0], "symbol": m["sg"][1]},
                "lattice": lattice,
                "basis": m["basis"],
            },
            "orientations": m["orientations"],
            "terminations": [{
                "id": "ideal-bulk", "orientation": m["orientations"][0],
                "description": "Ideal bulk truncation with no reconstruction applied.",
                "implemented": True,
            }],
            "reconstructions": [],
            "properties": prop_block(m["props"]),
            "recommended_models": m["models"],
            "references": sorted({v[3] for v in m["props"].values()} | {m["lattice_source"]}),
            "license": "CC0-1.0",
            "provenance_note": (
                "Generated by tools/gen_crystal_materials.py; basis expanded from the published "
                "Wyckoff parameters of the cited structure determination. "
                + m.get("note", "")
            ).strip(),
        }
        path = os.path.join(OUT, f"{doc['id']}.json")
        with open(path, "w") as fh:
            json.dump(doc, fh, indent=2)
            fh.write("\n")
        print("wrote", os.path.relpath(path), f"({len(doc['structure']['basis'])} basis sites)")


if __name__ == "__main__":
    main()
